-- MySQL Script generated by MySQL Workbench
-- Thu Oct 10 14:54:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agent` (
  `agent_id` INT NOT NULL,
  `agent_fname` VARCHAR(45) NULL,
  `agent_lname` VARCHAR(45) NULL,
  `agent_cnum` VARCHAR(45) NULL,
  PRIMARY KEY (`agent_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`caterer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`caterer` (
  `id` INT NOT NULL,
  `cat_package` VARCHAR(45) NOT NULL,
  `cat_cnum` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manager` (
  `id` INT NOT NULL,
  `man_fname` VARCHAR(45) NULL,
  `man_lname` VARCHAR(45) NULL,
  `man_cnum` INT NULL,
  `` VARCHAR(45) NULL,
  `caterer_id` INT NULL,
  PRIMARY KEY (`id`, `caterer_id`),
  INDEX `fk_manager_caterer1_idx` (`caterer_id` ASC) VISIBLE,
  CONSTRAINT `fk_manager_caterer1`
    FOREIGN KEY (`caterer_id`)
    REFERENCES `mydb`.`caterer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id` INT NOT NULL,
  `cus_fname` VARCHAR(45) NOT NULL,
  `cus_lname` VARCHAR(45) NOT NULL,
  `cus_cname` VARCHAR(45) NOT NULL,
  `cus_count` INT NOT NULL,
  `cus_type` VARCHAR(45) NOT NULL,
  `agent_agent_id` INT NOT NULL,
  PRIMARY KEY (`id`, `agent_agent_id`),
  INDEX `fk_customer_agent1_idx` (`agent_agent_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_agent1`
    FOREIGN KEY (`agent_agent_id`)
    REFERENCES `mydb`.`agent` (`agent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservation` (
  `id` INT NOT NULL,
  `res_date` DATE NOT NULL,
  `res_event` VARCHAR(45) NOT NULL,
  `manager_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `customer_agent_agent_id` INT NOT NULL,
  PRIMARY KEY (`id`, `manager_id`, `customer_id`, `customer_agent_agent_id`),
  INDEX `fk_reservation_manager1_idx` (`manager_id` ASC) VISIBLE,
  INDEX `fk_reservation_customer1_idx` (`customer_id` ASC, `customer_agent_agent_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_manager1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `mydb`.`manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_customer1`
    FOREIGN KEY (`customer_id` , `customer_agent_agent_id`)
    REFERENCES `mydb`.`customer` (`id` , `agent_agent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`photographer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`photographer` (
  `id` INT NOT NULL,
  `photo_name` VARCHAR(45) NOT NULL,
  `photo_package` VARCHAR(45) NOT NULL,
  `photo_cnum` INT NOT NULL,
  `manager_id` INT NOT NULL,
  `manager_caterer_id` INT NOT NULL,
  PRIMARY KEY (`id`, `manager_id`, `manager_caterer_id`),
  INDEX `fk_photographer_manager1_idx` (`manager_id` ASC, `manager_caterer_id` ASC) VISIBLE,
  CONSTRAINT `fk_photographer_manager1`
    FOREIGN KEY (`manager_id` , `manager_caterer_id`)
    REFERENCES `mydb`.`manager` (`id` , `caterer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
